title           = "Relaxing Clock"
languageCode    = "en-us"
disableKinds    = ["taxonomy", "term","RSS"]

[build]
  noJSConfigInAssets = true

[params]
  author    = "mijorus"
  desc      = "Relaxing Clock is just an awesome way to relax yourself - Powered by Spotify. It can play a great selection of Lo-Fi music with a minimalistic UI. You can also set alarms, start the Pomodoro Timer and sync the clock with the Internet to get the right time" 
  github    = "https://github.com/mijorus/RelaxingClock"
  instagram = "https://www.instagram.com/relaxingclock/"
  spotify   = "https://open.spotify.com/playlist/4ZTZhFPPyRzpfHZsWEXAW9?si=kvCqe0nMSdGbSmOB5ccQWA"
